<?php

// =============================================================================
// FUNCTIONS/INCLUDES/CURRENCY-LIST.PHP
// -----------------------------------------------------------------------------
// List of ISO-4217 Currency Codes in a PHP array
// =============================================================================

// =============================================================================
// TABLE OF CONTENTS
// -----------------------------------------------------------------------------
//   01. Array of values
// =============================================================================

// Array of values
// =============================================================================

return array (
  'AFN' => 'AFN - ' . __( 'Afghani', '__tco__' ),
  'EUR' => 'EUR - ' . __( 'Euro', '__tco__' ),
  'ALL' => 'ALL - ' . __( 'Lek', '__tco__' ),
  'DZD' => 'DZD - ' . __( 'Algerian Dinar', '__tco__' ),
  'USD' => 'USD - ' . __( 'US Dollar', '__tco__' ),
  'AOA' => 'AOA - ' . __( 'Kwanza', '__tco__' ),
  'XCD' => 'XCD - ' . __( 'East Caribbean Dollar', '__tco__' ),
  'ARS' => 'ARS - ' . __( 'Argentine Peso', '__tco__' ),
  'AMD' => 'AMD - ' . __( 'Armenian Dram', '__tco__' ),
  'AWG' => 'AWG - ' . __( 'Aruban Florin', '__tco__' ),
  'AUD' => 'AUD - ' . __( 'Australian Dollar', '__tco__' ),
  'AZN' => 'AZN - ' . __( 'Azerbaijanian Manat', '__tco__' ),
  'BSD' => 'BSD - ' . __( 'Bahamian Dollar', '__tco__' ),
  'BHD' => 'BHD - ' . __( 'Bahraini Dinar', '__tco__' ),
  'BDT' => 'BDT - ' . __( 'Taka', '__tco__' ),
  'BBD' => 'BBD - ' . __( 'Barbados Dollar', '__tco__' ),
  'BYN' => 'BYN - ' . __( 'Belarusian Ruble', '__tco__' ),
  'BYR' => 'BYR - ' . __( 'Belarusian Ruble', '__tco__' ),
  'BZD' => 'BZD - ' . __( 'Belize Dollar', '__tco__' ),
  'XOF' => 'XOF - ' . __( 'CFA Franc BCEAO', '__tco__' ),
  'BMD' => 'BMD - ' . __( 'Bermudian Dollar', '__tco__' ),
  'INR' => 'INR - ' . __( 'Indian Rupee', '__tco__' ),
  'BTN' => 'BTN - ' . __( 'Ngultrum', '__tco__' ),
  'BOB' => 'BOB - ' . __( 'Boliviano', '__tco__' ),
  'BOV' => 'BOV - ' . __( 'Mvdol', '__tco__' ),
  'BAM' => 'BAM - ' . __( 'Convertible Mark', '__tco__' ),
  'BWP' => 'BWP - ' . __( 'Pula', '__tco__' ),
  'NOK' => 'NOK - ' . __( 'Norwegian Krone', '__tco__' ),
  'BRL' => 'BRL - ' . __( 'Brazilian Real', '__tco__' ),
  'BND' => 'BND - ' . __( 'Brunei Dollar', '__tco__' ),
  'BGN' => 'BGN - ' . __( 'Bulgarian Lev', '__tco__' ),
  'BIF' => 'BIF - ' . __( 'Burundi Franc', '__tco__' ),
  'CVE' => 'CVE - ' . __( 'Cabo Verde Escudo', '__tco__' ),
  'KHR' => 'KHR - ' . __( 'Riel', '__tco__' ),
  'XAF' => 'XAF - ' . __( 'CFA Franc BEAC', '__tco__' ),
  'CAD' => 'CAD - ' . __( 'Canadian Dollar', '__tco__' ),
  'KYD' => 'KYD - ' . __( 'Cayman Islands Dollar', '__tco__' ),
  'CLP' => 'CLP - ' . __( 'Chilean Peso', '__tco__' ),
  'CLF' => 'CLF - ' . __( 'Unidad de Fomento', '__tco__' ),
  'CNY' => 'CNY - ' . __( 'Yuan Renminbi', '__tco__' ),
  'COP' => 'COP - ' . __( 'Colombian Peso', '__tco__' ),
  'COU' => 'COU - ' . __( 'Unidad de Valor Real', '__tco__' ),
  'KMF' => 'KMF - ' . __( 'Comoro Franc', '__tco__' ),
  'CDF' => 'CDF - ' . __( 'Congolese Franc', '__tco__' ),
  'NZD' => 'NZD - ' . __( 'New Zealand Dollar', '__tco__' ),
  'CRC' => 'CRC - ' . __( 'Costa Rican Colon', '__tco__' ),
  'HRK' => 'HRK - ' . __( 'Kuna', '__tco__' ),
  'CUP' => 'CUP - ' . __( 'Cuban Peso', '__tco__' ),
  'CUC' => 'CUC - ' . __( 'Peso Convertible', '__tco__' ),
  'ANG' => 'ANG - ' . __( 'Netherlands Antillean Guilder', '__tco__' ),
  'CZK' => 'CZK - ' . __( 'Czech Koruna', '__tco__' ),
  'DKK' => 'DKK - ' . __( 'Danish Krone', '__tco__' ),
  'DJF' => 'DJF - ' . __( 'Djibouti Franc', '__tco__' ),
  'DOP' => 'DOP - ' . __( 'Dominican Peso', '__tco__' ),
  'EGP' => 'EGP - ' . __( 'Egyptian Pound', '__tco__' ),
  'SVC' => 'SVC - ' . __( 'El Salvador Colon', '__tco__' ),
  'ERN' => 'ERN - ' . __( 'Nakfa', '__tco__' ),
  'ETB' => 'ETB - ' . __( 'Ethiopian Birr', '__tco__' ),
  'FKP' => 'FKP - ' . __( 'Falkland Islands Pound', '__tco__' ),
  'FJD' => 'FJD - ' . __( 'Fiji Dollar', '__tco__' ),
  'XPF' => 'XPF - ' . __( 'CFP Franc', '__tco__' ),
  'GMD' => 'GMD - ' . __( 'Dalasi', '__tco__' ),
  'GEL' => 'GEL - ' . __( 'Lari', '__tco__' ),
  'GHS' => 'GHS - ' . __( 'Ghana Cedi', '__tco__' ),
  'GIP' => 'GIP - ' . __( 'Gibraltar Pound', '__tco__' ),
  'GTQ' => 'GTQ - ' . __( 'Quetzal', '__tco__' ),
  'GBP' => 'GBP - ' . __( 'Pound Sterling', '__tco__' ),
  'GNF' => 'GNF - ' . __( 'Guinea Franc', '__tco__' ),
  'GYD' => 'GYD - ' . __( 'Guyana Dollar', '__tco__' ),
  'HTG' => 'HTG - ' . __( 'Gourde', '__tco__' ),
  'HNL' => 'HNL - ' . __( 'Lempira', '__tco__' ),
  'HKD' => 'HKD - ' . __( 'Hong Kong Dollar', '__tco__' ),
  'HUF' => 'HUF - ' . __( 'Forint', '__tco__' ),
  'ISK' => 'ISK - ' . __( 'Iceland Krona', '__tco__' ),
  'IDR' => 'IDR - ' . __( 'Rupiah', '__tco__' ),
  'XDR' => 'XDR - ' . __( 'SDR (Special Drawing Right)', '__tco__' ),
  'IRR' => 'IRR - ' . __( 'Iranian Rial', '__tco__' ),
  'IQD' => 'IQD - ' . __( 'Iraqi Dinar', '__tco__' ),
  'ILS' => 'ILS - ' . __( 'New Israeli Sheqel', '__tco__' ),
  'JMD' => 'JMD - ' . __( 'Jamaican Dollar', '__tco__' ),
  'JPY' => 'JPY - ' . __( 'Yen', '__tco__' ),
  'JOD' => 'JOD - ' . __( 'Jordanian Dinar', '__tco__' ),
  'KZT' => 'KZT - ' . __( 'Tenge', '__tco__' ),
  'KES' => 'KES - ' . __( 'Kenyan Shilling', '__tco__' ),
  'KPW' => 'KPW - ' . __( 'North Korean Won', '__tco__' ),
  'KRW' => 'KRW - ' . __( 'Won', '__tco__' ),
  'KWD' => 'KWD - ' . __( 'Kuwaiti Dinar', '__tco__' ),
  'KGS' => 'KGS - ' . __( 'Som', '__tco__' ),
  'LAK' => 'LAK - ' . __( 'Kip', '__tco__' ),
  'LBP' => 'LBP - ' . __( 'Lebanese Pound', '__tco__' ),
  'LSL' => 'LSL - ' . __( 'Loti', '__tco__' ),
  'ZAR' => 'ZAR - ' . __( 'Rand', '__tco__' ),
  'LRD' => 'LRD - ' . __( 'Liberian Dollar', '__tco__' ),
  'LYD' => 'LYD - ' . __( 'Libyan Dinar', '__tco__' ),
  'CHF' => 'CHF - ' . __( 'Swiss Franc', '__tco__' ),
  'MOP' => 'MOP - ' . __( 'Pataca', '__tco__' ),
  'MKD' => 'MKD - ' . __( 'Denar', '__tco__' ),
  'MGA' => 'MGA - ' . __( 'Malagasy Ariary', '__tco__' ),
  'MWK' => 'MWK - ' . __( 'Malawi Kwacha', '__tco__' ),
  'MYR' => 'MYR - ' . __( 'Malaysian Ringgit', '__tco__' ),
  'MVR' => 'MVR - ' . __( 'Rufiyaa', '__tco__' ),
  'MRO' => 'MRO - ' . __( 'Ouguiya', '__tco__' ),
  'MUR' => 'MUR - ' . __( 'Mauritius Rupee', '__tco__' ),
  'XUA' => 'XUA - ' . __( 'ADB Unit of Account', '__tco__' ),
  'MXN' => 'MXN - ' . __( 'Mexican Peso', '__tco__' ),
  'MXV' => 'MXV - ' . __( 'Mexican Unidad de Inversion (UDI)', '__tco__' ),
  'MDL' => 'MDL - ' . __( 'Moldovan Leu', '__tco__' ),
  'MNT' => 'MNT - ' . __( 'Tugrik', '__tco__' ),
  'MAD' => 'MAD - ' . __( 'Moroccan Dirham', '__tco__' ),
  'MZN' => 'MZN - ' . __( 'Mozambique Metical', '__tco__' ),
  'MMK' => 'MMK - ' . __( 'Kyat', '__tco__' ),
  'NAD' => 'NAD - ' . __( 'Namibia Dollar', '__tco__' ),
  'NPR' => 'NPR - ' . __( 'Nepalese Rupee', '__tco__' ),
  'NIO' => 'NIO - ' . __( 'Cordoba Oro', '__tco__' ),
  'NGN' => 'NGN - ' . __( 'Naira', '__tco__' ),
  'OMR' => 'OMR - ' . __( 'Rial Omani', '__tco__' ),
  'PKR' => 'PKR - ' . __( 'Pakistan Rupee', '__tco__' ),
  'PAB' => 'PAB - ' . __( 'Balboa', '__tco__' ),
  'PGK' => 'PGK - ' . __( 'Kina', '__tco__' ),
  'PYG' => 'PYG - ' . __( 'Guarani', '__tco__' ),
  'PEN' => 'PEN - ' . __( 'Sol', '__tco__' ),
  'PHP' => 'PHP - ' . __( 'Philippine Peso', '__tco__' ),
  'PLN' => 'PLN - ' . __( 'Zloty', '__tco__' ),
  'QAR' => 'QAR - ' . __( 'Qatari Rial', '__tco__' ),
  'RON' => 'RON - ' . __( 'Romanian Leu', '__tco__' ),
  'RUB' => 'RUB - ' . __( 'Russian Ruble', '__tco__' ),
  'RWF' => 'RWF - ' . __( 'Rwanda Franc', '__tco__' ),
  'SHP' => 'SHP - ' . __( 'Saint Helena Pound', '__tco__' ),
  'WST' => 'WST - ' . __( 'Tala', '__tco__' ),
  'STD' => 'STD - ' . __( 'Dobra', '__tco__' ),
  'SAR' => 'SAR - ' . __( 'Saudi Riyal', '__tco__' ),
  'RSD' => 'RSD - ' . __( 'Serbian Dinar', '__tco__' ),
  'SCR' => 'SCR - ' . __( 'Seychelles Rupee', '__tco__' ),
  'SLL' => 'SLL - ' . __( 'Leone', '__tco__' ),
  'SGD' => 'SGD - ' . __( 'Singapore Dollar', '__tco__' ),
  'XSU' => 'XSU - ' . __( 'Sucre', '__tco__' ),
  'SBD' => 'SBD - ' . __( 'Solomon Islands Dollar', '__tco__' ),
  'SOS' => 'SOS - ' . __( 'Somali Shilling', '__tco__' ),
  'SSP' => 'SSP - ' . __( 'South Sudanese Pound', '__tco__' ),
  'LKR' => 'LKR - ' . __( 'Sri Lanka Rupee', '__tco__' ),
  'SDG' => 'SDG - ' . __( 'Sudanese Pound', '__tco__' ),
  'SRD' => 'SRD - ' . __( 'Surinam Dollar', '__tco__' ),
  'SZL' => 'SZL - ' . __( 'Lilangeni', '__tco__' ),
  'SEK' => 'SEK - ' . __( 'Swedish Krona', '__tco__' ),
  'CHE' => 'CHE - ' . __( 'WIR Euro', '__tco__' ),
  'CHW' => 'CHW - ' . __( 'WIR Franc', '__tco__' ),
  'SYP' => 'SYP - ' . __( 'Syrian Pound', '__tco__' ),
  'TWD' => 'TWD - ' . __( 'New Taiwan Dollar', '__tco__' ),
  'TJS' => 'TJS - ' . __( 'Somoni', '__tco__' ),
  'TZS' => 'TZS - ' . __( 'Tanzanian Shilling', '__tco__' ),
  'THB' => 'THB - ' . __( 'Baht', '__tco__' ),
  'TOP' => 'TOP - ' . __( 'Pa’anga', '__tco__' ),
  'TTD' => 'TTD - ' . __( 'Trinidad and Tobago Dollar', '__tco__' ),
  'TND' => 'TND - ' . __( 'Tunisian Dinar', '__tco__' ),
  'TRY' => 'TRY - ' . __( 'Turkish Lira', '__tco__' ),
  'TMT' => 'TMT - ' . __( 'Turkmenistan New Manat', '__tco__' ),
  'UGX' => 'UGX - ' . __( 'Uganda Shilling', '__tco__' ),
  'UAH' => 'UAH - ' . __( 'Hryvnia', '__tco__' ),
  'AED' => 'AED - ' . __( 'UAE Dirham', '__tco__' ),
  'USN' => 'USN - ' . __( 'US Dollar (Next day)', '__tco__' ),
  'UYU' => 'UYU - ' . __( 'Peso Uruguayo', '__tco__' ),
  'UYI' => 'UYI - ' . __( 'Uruguay Peso en Unidades Indexadas (URUIURUI)', '__tco__' ),
  'UZS' => 'UZS - ' . __( 'Uzbekistan Sum', '__tco__' ),
  'VUV' => 'VUV - ' . __( 'Vatu', '__tco__' ),
  'VEF' => 'VEF - ' . __( 'Bolívar', '__tco__' ),
  'VND' => 'VND - ' . __( 'Dong', '__tco__' ),
  'YER' => 'YER - ' . __( 'Yemeni Rial', '__tco__' ),
  'ZMW' => 'ZMW - ' . __( 'Zambian Kwacha', '__tco__' ),
  'ZWL' => 'ZWL - ' . __( 'Zimbabwe Dollar', '__tco__' ),
  'XBA' => 'XBA - ' . __( 'Bond Markets Unit European Composite Unit (EURCO)', '__tco__' ),
  'XBB' => 'XBB - ' . __( 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', '__tco__' ),
  'XBC' => 'XBC - ' . __( 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', '__tco__' ),
  'XBD' => 'XBD - ' . __( 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', '__tco__' ),
  'XTS' => 'XTS - ' . __( 'Codes specifically reserved for testing purposes', '__tco__' ),
  'XXX' => 'XXX - ' . __( 'The codes assigned for transactions where no currency is involved', '__tco__' ),
  'XAU' => 'XAU - ' . __( 'Gold', '__tco__' ),
  'XPD' => 'XPD - ' . __( 'Palladium', '__tco__' ),
  'XPT' => 'XPT - ' . __( 'Platinum', '__tco__' ),
  'XAG' => 'XAG - ' . __( 'Silver', '__tco__' ),
);
